# Site Configuration
title: "Clemz Student Scoreboard"
description: "Mathematics and Science Scoreboard for RRCR, PJPA, and DLA."
baseurl: "/Clemz-New-Scoreboard"  # Repository name
url: "https://clemzclems.github.io"  # GitHub Pages base URL
markdown: kramdown
theme: minima  # Optional, but good to specify a theme

# Site Branding
logo: "/assets/images/logo.png"         # School logo (200x200px recommended)
favicon: "/assets/images/favicon.png"   # Favicon (32x32px recommended)
banner: "/assets/images/banner.jpg"     # Header banner (1200x400px recommended)
# Collections
collections:
  posts:
    output: true
  rrcr_tables:
    output: true
    permalink: /RRCR/:path/
  pjpa_tables:
    output: true
    permalink: /PJPA/:path/
  dla_tables:
    output: true
    permalink: /DLA/:path/

# Markdown Configuration
markdown_ext: "markdown,md"
permalink: pretty
