# Site Configuration
title: "Clemz Student Scoreboard"
description: "Mathematics and Science Scoreboard for RRCR, PJPA, and DLA."
baseurl: "/Clemz-New-Scoreboard"  # Ensure this matches the repository name
url: "https://clemzclems.github.io"  # GitHub Pages URL
markdown: kramdown
theme: minima

# Site Branding
logo: "{{ site.baseurl }}/assets/images/logo.png"       # Correct image path
favicon: "{{ site.baseurl }}/assets/images/favicon.png"  # Correct image path
banner: "{{ site.baseurl }}/assets/images/banner.jpg"    # Correct image path

# Beautiful Author Info
author:
  name: "Clemz Clems"
  email: "your-email@example.com"
  bio: "Innovative educator passionate about simplifying Mathematics and Science for young minds."
  photo: "{{ site.baseurl }}/assets/images/author.jpg"  # Correct image path
  social:
    facebook: "https://www.facebook.com/profile.php?id=100004792087165"
    instagram: "https://www.instagram.com/clemzclems/"
    twitter: "https://x.com/DrClem88"
    youtube: "https://www.youtube.com/@MathCraft3D"
    paypal: "https://paypal.me/clemzclems?country.x=AE&locale.x=en_US"
    formspree: "https://formspree.io/f/mwpvdgeo"

# Collections
collections:
  posts:
    output: true
  rrcr_tables:
    output: true
    permalink: /RRCR/:path/
  pjpa_tables:
    output: true
    permalink: /PJPA/:path/
  dla_tables:
    output: true
    permalink: /DLA/:path/

# Markdown Configuration
markdown_ext: "markdown,md"
permalink: pretty
